<?php

namespace App\Http\Requests;

use App\Exceptions\ApiException;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class ApiRequest extends FormRequest
{
  public function messages(): array
  {
    return parent::messages(); // TODO: Change the autogenerated stub
  }

  protected function failedAuthorization(): void
  {
    throw new ApiException(401, 'Вы не авторизованы');
  }

  protected function failedValidation(Validator $validator): void
  {
    throw new ApiException(422, 'Ошибка валидации данных', $validator->errors());
  }
}
